### PR TITLE
[bug] check if 'enabled' field exist in the Identity document

### PR DESCRIPTION
**Pull request by meskio**
- Related: #7961

### CODE REVIEW

**Comment by elijh** [comment]
i think that should be:

                     if "enabled" not in doc or doc["enabled"]:

**Comment by meskio** [comment]
I see, so if there is no 'enabled' field in the Indentity document this means that the account is enabled? Weird but I can do it like that.

**Comment by elijh** [comment]
i tested that out and it seems to work correctly with enabling and disabling users, and with users with missing 'enabled'. i wasn't sure if doc["enabled"] value of "false" would be really be treated as false, but i guess it converts it from string to boolean somewhere.

**Comment by elijh** [comment]
yes, a missing 'enabled' field means it was a legacy record before 'enabled' field was added, so it should be treated as enabled.

**Comment by meskio** [comment]
Updated the pull-req with the new logic.

I think json couch document is converted to a python dict and the boolean values are converted correctly. But not completely sure about it.

**Pull request merged**
